MvcProjectCamp/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayerr.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MvcProjectCamp.Controllers
{
    public class AuthorizationController : Controller
    {
        // GET: Authorization

        AdminManager adm = new AdminManager(new EfAdminDal());
        public ActionResult Index()
        {
            var adminvalues = adm.GetList();
            return View(adminvalues);
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            adm.AdminAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            List<SelectListItem> role = (from x in adm.GetList()
                                         select new SelectListItem
                                         {
                                             Text = x.AdminRole,
                                             Value = x.AdminRole
                                         }).ToList();
            ViewBag.role = role;
            var adminvalue = adm.GetByID(id);
            return View(adminvalue);
        }
        [HttpPost]
        public ActionResult EditAdmin(Admin p)
        {
            p.AdminStatus = true;
            adm.AdminUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAdmin(int id)
        {
            var values = adm.GetByID(id);
            if (values.AdminStatus == true)
            {
                values.AdminStatus = false;
            }
            else if (values.AdminStatus == false)
            {
                values.AdminStatus = true;
            }

            adm.AdminUpdate(values);

            return RedirectToAction("Index");

        }
    }
}

MvcProjectCamp/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Admin Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
    <div class=" form-group">
        @Html.Label("Admin Kullanıcı Adı:")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifreyi Giriniz")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Rolü Seçiniz")
        @*@Html.DropDownListFor(x => x.AdminRole, (List<SelectListItem>)ViewBag.role, new { @class = "form-control" })*@
        @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-warning">Kaydet</button>
    </div>
}

MvcProjectCamp/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2 style="font-weight: bold">Admin Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
    <div class=" form-group">
        @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Admin Rolü")
        @Html.DropDownListFor(x => x.AdminRole, (List<SelectListItem>)ViewBag.role, new { @class = "form-control" })
        <br />
        <button class=" btn btn-outline-success">Güncelle</button>
    </div>
}

MvcProjectCamp/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    int count = 0;
    string colour = "";
    string status = "";
    string buttonname = "";
    string buttoncolor = "";
}

@*<br />
<table class=" table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Statü</th>
        <th>Pasif Yap</th>
        <th>Yetkisini Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AdminID</td>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
        </tr>
    }
</table>
<br />
<a href="/Authorization/AddAdmin/" class="btn btn-outline-info">Yeni Admin Tanımla</a>*@


<div>
    <br />
    <br />
    <h3 class="container card-header">Admin Listesi</h3>

    <table class="table table-striped container">
        <tr>
            <th>#</th>
            <th>Kullanıcı Mail</th>
            <th>Yetki</th>
            <th>Durum</th>
            <th>Yetki Değiştir</th>
            <th>İşlem</th>
        </tr>

        @foreach(var item in Model)
        {
            count++;
            if (item.AdminStatus == false) { colour = "danger"; }
            if (item.AdminStatus == true) { colour = "success"; }
            if (item.AdminStatus == false) { status = "Pasif"; }
            if (item.AdminStatus == true) { status = "Aktif"; }
            if (item.AdminStatus == false) { buttoncolor = "success"; }
            if (item.AdminStatus == true) { buttoncolor = "danger"; }
            if (item.AdminStatus == false) { buttonname = "Aktif Yap"; }
            if (item.AdminStatus == true) { buttonname = "Pasif Yap"; }
            <tr>
                <th>@count</th>
                <th>@item.AdminUserName</th>
                <th>@item.AdminRole</th>

                <td class="project-state">
                    <span class="badge badge-@colour">@status</span>
                </td>
                <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-outline-info"><i class="fas fa-edit"></i>Yetkisini Değiştir</a></td>
                <td><a href="/Authorization/DeleteAdmin/@item.AdminID" class="btn btn-@buttoncolor"><i class="fas fa-arrow-alt-circle-left"></i>@buttonname</a></td>
            </tr>
        }
    </table>
</div>
<div class="container">
    <a href="/Authorization/AddAdmin/" class="btn btn-outline-info">Yeni Admin Tanımla</a>
</div>