MvcProjectCamp/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayerr.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MvcProjectCamp.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutvalues = abm.GetList();
            return View(aboutvalues);
        }

        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            abm.AboutAdd(p);
            return RedirectToAction("Index");
        }

        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
        public ActionResult DeleteAbout(int id)
        {
         
            return RedirectToAction("Index");
        }
    }
}

MvcProjectCamp/Views/About/AboutPartial.cshtml
<button class="btn btn-outline-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Hakkımızda Yazı Girişi
</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Yazı Metin Girişi</h2>
            </div>
            <form method="post" action="/About/AddAbout/">
                <div class="modal-body">
                    <label>Hakkımda Metin 1</label>
                    <input type="text" name="AboutDetails1" class="form-control" />
                    <br />
                    <label>Hakkımda Metin 2</label>
                    <input type="text" name="AboutDetails2" class="form-control" />
                    <br />
                    <label>Hakkımda Görsel 1</label>
                    <input type="text" name="AboutImage1" class="form-control" />
                    <br />
                    <label>Hakkımda Görsel 2</label>
                    <input type="text" name="AboutImage2" class="form-control" />
                    <br />
                    <button class="btn btn-outline-info">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

MvcProjectCamp/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    string status = "";
    string buttonname = "";
    string buttoncolor = "";
    string colour = "";
}

<h2>Hakkımda Veri Listesi</h2>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Açıklama 1</th>
        <th>Açıklama 2</th>
        <th>Görsel 1</th>
        <th>Görsel 2</th>
        <th>Durum</th>
        <th>Düzenle</th>
        <th>İşlem</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.AboutStatus == false) { status = "Pasif"; }
        if (item.AboutStatus == true) { status = "Aktif"; }
        if (item.AboutStatus == false) { buttoncolor = "success"; }
        if (item.AboutStatus == true) { buttoncolor = "danger"; }
        if (item.AboutStatus == false) { buttonname = "Aktif Yap"; }
        if (item.AboutStatus == true) { buttonname = "Pasif Yap"; }
        if (item.AboutStatus == false) { colour = "Danger"; }
        if (item.AboutStatus == true) { colour = "Success"; }

        <tr>
            <td>@item.AboutID</td>
            <td>@item.AboutDetails1</td>
            <td>@item.AboutDetails2</td>
            <td>@item.AboutImage1</td>
            <td>@item.AboutImage2</td>
            <td class="project-state">
                <span class="badge badge-@colour">@status</span>
            </td>
            <td>
                <a href="/About/UpdateAbout/@item.AboutID" class="btn btn-info">
                    <i class="fas fa-pencil-alt">
                    </i>Düzenle
                </a>
            </td>
            <td>
                <a href="/About/DeleteAbout/@item.AboutID" class="btn btn-@buttoncolor">
                    <i class="fas fa-arrow-alt-circle-left">
                    </i>@buttonname
                </a>
            </td>
        </tr>
    }
</table>

@Html.Action("AboutPartial", "About")